### ISSUE TITLE
Sleeves not unlocking?

### ISSUE THREAD

**Issue by ravenCG** [larswijn/CardSleeves#2]
I just downloaded the mod today, got on and saw that it didn't unlock from blinds I previously completed, nbd, so I went and did a quick purple stake run on plasma and it didn't unlock after that, tried orange, it didn't unlock, then finally did a gold stake run, and it still didn't unlock so I'm assuming I either did something wrong or there is something fucky going on with the mod
![image](https://github.com/user-attachments/assets/d77c8fa8-29b4-4899-a8e9-284c3ec2d281)

**Comment by larswijn** [comment]
Weird. The sleeves should automatically unlock retroactively on install.

This used to be an incompatibility issue with Grim V0.9.5 or older.
Could you let me know if you have an outdated version of the Grim mod, or if not, your full mod list?

**Comment by larswijn** [comment]
Assumed to be an issue with an outdated version of the Grim mod.
I've added an incompatibility check with 9f555e1, included in [V1.4.7](https://github.com/larswijn/CardSleeves/releases/tag/v1.4.7).
